### ISSUE TITLE
curl command  https://<ORG>.testsliderule.org/source/version returns '%' at end of response

### ISSUE THREAD

**Issue by cugarteblair** [ICESat2-SlideRule/sliderule#134]
curl -L https://Developers.testsliderule.org/source/version 
{"icesat2":{"commit":"v1.4.6-153-gcf8a096","version":"1.4.6"},"server":{"version":"1.4.6","commit":"v1.4.6-153-gcf8a096","duration":238094,"packages":["core","aws","geotiff","h5","netsvc","icesat2"],"launch":"2022-08-31T14:43:42Z"}}%

**Comment by jpswinski** [comment]
This percent sign shows up for other requests in @cugarteblair's system - requests that only use curl and the provisioning system.  So it appears very likely that the issue is the construction of the prompt within vscode.
