### ISSUE TITLE
RqstParms to support radius and sampling algorithm

### ISSUE THREAD

**Issue by jpswinski** [ICESat2-SlideRule/sliderule#166]
The user needs to be able to specify the radius and sampling algorithm to use when sampling a raster for the atl06 api.  This functionality needs to be added to the RqstParms class and the corresponding endpoint rqst json structure needs to be updated.

**Comment by dshean** [comment]
👍 While circular radius is priority, it would be good to keep this general to define more complex sampling areas around the atl06 points for zonal stats (e.g., some buffer around the ground track for the ATL06 segment).

**Comment by jpswinski** [comment]
Complete
