### ISSUE TITLE
Sliderule client should display http errors on failed requests

### ISSUE THREAD

**Issue by jpswinski** [ICESat2-SlideRule/sliderule#26]
The sliderule.py client currently does not display (even when verbose set to true) any http level errors like "Not Found" or "Bad Request" when those errors occur.  It just fails silently.

**Comment by jpswinski** [comment]
The SlideRule Python client now catches three types of TCP/IP errors:
* ConnectionError
* HTTPError
* Timeout

It prints a user-friendly message to the user when one of these errors is caught.

**Comment by arnab-muhuri** [comment]
Why does it displays HTTP Request Error even when the granules are found?

**Comment by jpswinski** [comment]
@arnab-muhuri Can you provide an example of what is being displayed; and also, if it is okay, can you provide the request you are making, including the parameters?

**Comment by arnab-muhuri** [comment]
cmr_parms = {
      "asset": "icesat2",
      "poly": poly,
      "version": '006'
      #"poly": region["poly"]
  }

  from sliderule import earthdata
  earthdata.set_max_resources(1000)

  grns = earthdata.search(cmr_parms)

and the error that I get is this

ERROR:sliderule.sliderule:HTTP Request Error: HTTP Error 400: Bad Request
WARNING:sliderule.sliderule:Using simplified polygon (for CMR request only!), 5 points using tolerance of 0.0001

**Comment by arnab-muhuri** [comment]
What's the syntax for adding a datetime object in cmr_parms?

**Comment by jpswinski** [comment]
The reason for the error is that CMR is rejecting the initial polygon being sent to it.  There are certain criteria that the polygon has to meet in order for CMR to accept and use the polygon.  The SlideRule client has logic in it where if CMR rejects a request due to a polygon being too complex or not meeting all the requirements, it automatically tries to simplify the polygon and resubmit the request.

That is what is happening here.  The first polygon was rejected by CMR.  SlideRule printed the error and then retried the request with a simplified polygon.  That request was accepted and the granule names were returned.

**Comment by arnab-muhuri** [comment]
So the polygon is still the polygon that I requested but simplified in terms of the coordinates? 
Can t0 an t1 be the same dates?

**Comment by jpswinski** [comment]
The polygon that ultimately gets sent to SlideRule is still the original one, but the one that is sent to CMR is modified (buffered and simplified) from the original.  This is necessary in order to get a response from CMR.  There is a possibility that some of the granules returned by CMR don't actually intersect the initial polygon (but that is always a possibility even when the initial polygon is accepted).

I don't know about t0 and t1 being the same dates.  I've always had them at least 1 day apart.

**Comment by arnab-muhuri** [comment]
Alrighty :)
