### ISSUE TITLE
Replace "nodata" value with NaN as sampled value in GeoRaster

### ISSUE THREAD

**Issue by jpswinski** [ICESat2-SlideRule/sliderule#262]
When sampling a raster and returning the sampled result, if the value is the "nodata" value, then instead of returning it, return NaN instead.  This is because the user doesn't have access to the original TIFF file and cannot unambiguously know if a value is the "nodata" value or not.

**Comment by elidwa** [comment]
Fixed on branch xyz
https://github.com/ICESat2-SlideRule/sliderule/commit/03b2d20446eb85063b5cf53150dc4b337b25b8b6

**Comment by jpswinski** [comment]
Released in v3.5.0
