### ISSUE TITLE
Make default number of ATL06 iterations 6

### ISSUE THREAD

**Issue by dshean** [ICESat2-SlideRule/sliderule#280]

**Comment by dshean** [comment]
Ah, OK.  I'll let Ben weigh in.  The demo is still pegged at 1.

@tsutterley was going to look at implementing some of the basic relationships we've discussed around segment width, step size, number of photons, etc.

**Comment by SmithB** [comment]
5 and 6 should produce very similar results.  The only change that was really needed was the change in the demo, and @tsutterley has nailed that.  Thanks, all!
