### ISSUE TITLE
feature request: report y_atc in ATL06-SR

### ISSUE THREAD

**Issue by SmithB** [ICESat2-SlideRule/sliderule#283]
The across-track coordinate of the segments would be a helpful parameter to at least some users.  in ATL06 proper, this is the y_atc parameter, and it's calculated based on averages of the ATL03 across-track photon location parameter.

**Comment by jpswinski** [comment]
This has been implemented.  It is calculated the same way as the latitude, longitude, and time - as a lsf on remaining photons in the window.
