### ISSUE TITLE
Feature idea : extract arbitrary fields from ATL03 to ATL06-SR

### ISSUE THREAD

**Issue by SmithB** [ICESat2-SlideRule/sliderule#284]
Allow the ATL06-SR algorithm to calculate per-segment averages of arbitrary ATL03 fields, based on the final photon selection.  User would pass a list of parameters, slideRule would determine whether the parameters are provided by ATL03 at the segment level or the photon level, and either average over selected photons or interpolate in time to the segment centers for each parameter.

**Comment by mochell** [comment]
Thats be great. A workaround would be allowing the same field retrieval in ATL06 and in the [ATL03 algorithm](hook://email/12.CF.09931.9DE03C46%40ge.mta3vrest.cc.prd.sparkpost).

**Comment by jpswinski** [comment]
This is completed - ancillary fields run through the same ATL06 LSF algorithm as the photon heights, latitude, and longitude.
