### ISSUE TITLE
The certificate for sliderule.slideruleearth.io expired on 19/07/2023.

### ISSUE THREAD

**Issue by cscottwatson** [ICESat2-SlideRule/sliderule#285]
Hello, it seems the SSL certificate has expired, causing an error:
![SSL_error](https://github.com/ICESat2-SlideRule/sliderule/assets/13930038/18534a49-3671-4169-bb1b-ca8865d0fb19)

**Comment by scottyhq** [comment]
related: https://github.com/ICESat2-SlideRule/sliderule/issues/208

**Comment by jpswinski** [comment]
@cscottwatson sorry for the issue - it has been fixed for now.  I'll keep this issue open until we resolve #208 and then close them together.  If you continue to experience any problems, please post it here.

**Comment by jpswinski** [comment]
Issue #208 has been resolved; closing this issue.
