### ISSUE TITLE
Add ESA WorldCover plugin

### ISSUE THREAD

**Issue by jpswinski** [ICESat2-SlideRule/sliderule#293]
Add the 10m ESA WorldCover as raster asset for sampling: https://registry.opendata.aws/esa-worldcover-vito/

**Comment by jpswinski** [comment]
Given that this is just a single dataset; instead of creating a plugin just for this, maybe it would be better to create a plugin called `opendata` and this is just a class in that plugin.

**Comment by dshean** [comment]
Yeah, some generalization makes sense, though STAC support and availability of vrt/indices varies by dataset.  

Potentially also some differences in optimization for different cloud providers.  The AWS datasets should be easy, but there are some useful datasets (e.g., the 3DEP 2-m layers) that are currently only available on Planetary Computer.

**Comment by elidwa** [comment]
This has been implemented a while back. Closing.
