### ISSUE TITLE
Reqests to TNM for 3DEP 1m is timing out

### ISSUE THREAD

**Issue by jpswinski** [ICESat2-SlideRule/sliderule#295]
Requests to The National Map to query for the 3DEM 1m product are timing out (504).
```
$ curl https://tnmaccess.nationalmap.gov/api/v1/products?datasets=Digital+Elevation+Model+%28DEM%29+1+meter
{"message": "Endpoint request timed out"}
```

**Comment by jpswinski** [comment]
A general request to the domain works:
```
$ curl https://tnmaccess.nationalmap.gov
{"description": "TNM Access provides REST APIs to access the National Map (TNM) data", "href": "https://apps.nationalmap.gov/tnmaccess/", "documentation": "https://tnmaccess.nationalmap.gov/api/v1/docs", "version": "1.0.0", "build": "6a959706c2f18bb06e6a6b04d9c892a313336c8e"
```

**Comment by jpswinski** [comment]
When using the web interface "https://apps.nationalmap.gov/tnmaccess/#/product" provided by usgs and searching for the 1m DEM product using their drop down, it also responds with:
```
{"message": "Endpoint request timed out"}
```

**Comment by dshean** [comment]
I can confirm timeout via the Lidar Explorer.  

Really unfortunate timing with Hackweek event.  I'm looking for contact info of IT folks at USGS TNM and will contact them - hopefully a quick fix.  

<img width="1907" alt="USGS Lidar Explorer Map 2023-08-05 10-38-46" src="https://github.com/ICESat2-SlideRule/sliderule/assets/1103530/c11b4886-af02-4c10-9744-7c0e551a9c3a">

**Comment by dshean** [comment]
Email sent to tnm_help@usgs.gov.

**Comment by jpswinski** [comment]
There were facility issues at USGS that necessitated that this service be temporarily disabled.  It has since been re-enabled and things are back to normal.
