### ISSUE TITLE
Doc improvement: fix outdated hardcoded settings

### ISSUE THREAD

**Issue by dshean** [ICESat2-SlideRule/sliderule#373]
Just starting a thread to note as I see these.  Likely worth a find/replace for all docs...

Remove `"maxi": 1` from https://slideruleearth.io/web/rtd/getting_started/Getting-Started.html#basic-usage

**Comment by jpswinski** [comment]
All occurrences of `maxi` have been removed from examples.

**Comment by dshean** [comment]
Great!  I will keep opening issues as I find them, or just submit PRs if I have the time.  These are not urgent, just seems like incremental doc review/updates will be easier than dedicating large chunk of time to review everything.
