### ISSUE TITLE
Issues with reference delta_time in Everest output

### ISSUE THREAD

**Issue by dshean** [ICESat2-SlideRule/sliderule#46]
This may be an ATL03 product version issue.  

delta_time returned by SlideRule for ATL03-cloud over Everest region appears to have two reference times.  I see limited number (888) of values around 8.420037e+07, corresponding to products from early in missions 20181022, while most other values (~365K) are around 1.282008e+09.

My current workaround:
```
#Currently using astropy for GPS time handling
from astropy.time import Time

def time_convert(df):
    print("Converting GPS time to Pandas DateTime")
    
    #Some early ATL03 delta_time values use different reference epoch, need to correct these 
    t_ref1 = Time('2018-01-06T00:00:00', format='isot')
    t_ref2 = Time('1980-01-06T00:00:00', format='isot')
    t_off = t_ref1.gps - t_ref2.gps
    
    df.loc[df['delta_time'] < t_ref1.gps, 'delta_time'] += t_off 
    
    temp = Time(t_ref2.gps + df['delta_time'], format='gps')
    
    df['utc'] = pd.to_datetime(temp.isot)
    
    print("Converting timestamp to decyear")
    df['decyear'] = temp.decimalyear
    
    print("Resetting index and sorting")
    df.set_index('utc', inplace=True)
    df.sort_index(inplace=True)
```

**Comment by jpswinski** [comment]
@dshean I am unable to reproduce this issue.  Since Dec 2020, we are no longer using repacked ATL03 files, so it is possible that this was an issue with the rechunking process.  Can you check to see if this problem is still happening for you?

In addition to plotting the everest data for ATL06-SR and ATL03, I also did a quick check on the times:
```python
>>> len(atl06)
382297
>>> t1check = atl06[atl06["delta_time"] < 1.252008e+09]
>>> len(t1check)
179046
>>> t2check = atl06[atl06["delta_time"] < 1.232008e+09]
>>> len(t2check)
57522
>>> t3check = atl06[atl06["delta_time"] < 1.202008e+09]
>>> len(t3check)
```

**Comment by dshean** [comment]
OK, if you can't reproduce with latest version of SlideRule and ATL03 data, then I think we can close this issue.  I will experiment with latest workflows for Everest when I have some free time, hopefully in coming weeks.
