### ISSUE TITLE
Elevations are missing from some atl06 processing runs

### ISSUE THREAD

**Issue by jpswinski** [ICESat2-SlideRule/sliderule#92]
When running sliderule ATL06 processing against a region of interest, the vast majority of the time it returns the exact same data when the exact same parameters are supplied.

But intermittently, there are runs in which at least one granule will have fewer elevations returned - usually on the order of a few hundred or less.

**Comment by jpswinski** [comment]
On one occurrence the following error was captured:

```
2021-09-01T13:39:56.800Z 192.168.1.8:CRITICAL:Atl03Reader.cpp:724 Failure during processing of resource ATL03_20200812144249_07370802_004_01.h5 track 2: failed to inflate entire z_stream: -3 (/gt2l/signal_photons/classed_pc_indx)
```

**Comment by dshean** [comment]
Awesome!  Thanks @jpswinski.  I know this wasn't a trivial issue to understand and fix.
